# -*- coding: utf-8 -*-
"""Fake News Detection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Py7HjqTmeU3k8vzGo_FXk68IUl_HXmn_
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
import re
import string
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score

df = pd.read_csv("news.csv")

df

df.head(10)

df.loc[(df['label']==0), ['label']]='FAKE'
df.loc[(df['label']==1), ['label']]='REAL'

x_train, x_test, y_train, y_test = train_test_split(df['text'], df['label'], test_size=0.2, random_state = 42)

from sklearn.feature_extraction.text import TfidfVectorizer

vectorization = TfidfVectorizer(stop_words='english', max_df=0.7)

xv_train = vectorization.fit_transform(x_train)
xv_test = vectorization.transform(x_test)

from sklearn.linear_model import PassiveAggressiveClassifier

paclass=PassiveAggressiveClassifier(max_iter=50)

paclass.fit(xv_train, y_train)

pred=paclass.predict(xv_test)

xy=accuracy_score(y_test, pred)
print(f'Accuracy: {round(xy*100,2)}%')